spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-db:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auth_password}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.booktracker.auth: INFO
    org.hibernate.SQL: INFO
